# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_auto_20161129_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('detail', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transaction_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'db_table': 'transaction',
            },
        ),
    ]
