# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
