# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
