# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161017_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(default=1988),
        ),
    ]
