# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default=b'zh', max_length=2),
        ),
    ]
