# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.CharField(blank=True, max_length=32, null=True)),
                ('data_type', models.CharField(choices=[('s', 'string'), ('n', 'number'), ('b', 'boolean')], default='s', max_length=2)),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
