# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_albumn_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default=b'en', max_length=2),
        ),
    ]
