# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
