# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('host_score', models.IntegerField(blank=True, default=0, null=True)),
                ('guest_score', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.Team')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Season'),
        ),
    ]
