# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20161019_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
