# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playergamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamescore',
            name='starters',
            field=models.CharField(choices=[('Y', '\u9996\u53d1'), ('S', '\u66ff\u8865'), ('NP', '\u7f3a\u5e2d'), ('NA', '\u65e0\u6570\u636e')], default='NA', max_length=2),
        ),
    ]
