# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_albumn_image'),
        ('game', '0004_playergamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='albumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Albumn'),
        ),
        migrations.AlterField(
            model_name='playergamescore',
            name='starters',
            field=models.CharField(choices=[('Y', '\u9996\u53d1'), ('S', '\u66ff\u8865'), ('NP', '\u7f3a\u5e2d'), ('NA', '\u65e0\u6570\u636e')], default='NA', max_length=2),
        ),
    ]
