# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_image_weight'),
        ('game', '0005_auto_20161027_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Album'),
        ),
    ]
