# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20161104_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamescore',
            name='starters',
            field=models.CharField(choices=[('Y', 'Starter'), ('S', 'Substitutes'), ('NP', 'Not Play'), ('NA', 'N/A')], default='NA', max_length=2),
        ),
    ]
