# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='SystemSetting',
        ),
        migrations.AlterModelTable(
            name='systemsetting',
            table='system_setting',
        ),
    ]
