# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_auto_20161027_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='name',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
