# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_remove_player_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
