# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20161004_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamhistory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='teamhistory',
            name='created',
        ),
    ]
