# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20161004_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
