# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20161129_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
