# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20161010_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
